spring.application.name=JournalApp
spring.data.mongodb.uri=mongodb+srv://rohan150515454_db_user:owleBPZJLT1hzlO2@cluster0.ngmtybq.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true

#if username of password needed write these
#spring.data.mongodb.username=username
#spring.data.mongodb.password=password